# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nazmul Islam Ananto
author:
  name: Ananto
  email: nazmulislamananto@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Student at Bangladesh University of Engineering and Technology (BUET) studying
  Computer Science and Engineering (CSE).
# facebook_username: nazmulislamananto
# twitter_username: nazmul_ananto
# github_username: niananto
# linkedin_username: niananto
# instagram_username: ananto___
# reddit_username: niananto

baseurl: "/home" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# show_excerpts: true # is false by default

# Build settings
# highlighter: true
# markdown: kramdown
# permalink: pretty
# theme: minima
# theme: jekyll-theme-midnight
# theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-thumbnail
  # - jekyll-seo-tag

# collections_dir: collections
collections:
  projects:
    output: true
    permalink: /:collection/:path
  header-tabs:
    output: true
    # order: # this only works on jekyll v4.0 or higher, thus won't work on github as it uses v3.8.7
    #   - about.md
    #   - photo-gallery.md
    #   - projects.md
    #   - extra-curricular.md
    #   - resume.md
    #   - contact-me.md
  web-resume:
    output: true
    

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
